### ISSUE TITLE
Create the wireframe for the Web UI

### ISSUE THREAD

**Issue by fabdarice** [berf-chat/berf-web-ui#3]

**Comment by bayological** [comment]
Wireframe: https://wireframe.cc/lilR1j

**Comment by bayological** [comment]
@QuinnLee @RCantu92 
Hey guys not sure if you saw this but made an attempt at the wireframes yesterday.

**Comment by QuinnLee** [comment]
lgtm

I think we should pull in material-ui for components so we don't have to do the grunt work

**Comment by bayological** [comment]
@QuinnLee agreed. We can add a new ticket for it or add it as a task on an existing one.
