### ISSUE TITLE
SPIKE: Figure out how we can encrypt and decrypt a message

### ISSUE THREAD

**Issue by fabdarice** [berf-chat/berf-web-ui#6]

**Comment by bayological** [comment]
We can use this library to sign & encrypt/decrypt messages.
Eth-Crypto - [](https://www.npmjs.com/package/eth-crypto)

They have a simple tutorial on how to use it which is worth following to see it's use:
https://github.com/pubkey/eth-crypto/blob/master/tutorials/encrypted-message.md

Cryptography chapter in mastering Ethereum goes deeper into the math behind it:
https://github.com/ethereumbook/ethereumbook/blob/develop/04keys-addresses.asciidoc
